# Generated by Django 3.1.4 on 2022-03-08 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proprietaire', models.CharField(blank=0, choices=[('BAJAJ', 'BAJAJ'), ('MOTO', 'MOTO')], default='House', max_length=80, null=0)),
                ('Type', models.CharField(max_length=80)),
                ('plaque', models.CharField(blank=0, default='', max_length=80, null=0)),
                ('Numero_chasis', models.CharField(blank=0, default='', max_length=80, null=0)),
                ('CNI', models.CharField(blank=0, default='', max_length=80, null=0)),
                ('Adresse', models.CharField(blank=0, default='', max_length=80, null=0)),
                ('Telephone', models.CharField(blank=0, default='', max_length=80, null=0)),
            ],
        ),
    ]
