# Generated by Django 3.1.4 on 2022-03-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220309_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moto',
            name='id',
        ),
        migrations.AlterField(
            model_name='moto',
            name='plaque',
            field=models.CharField(blank=0, default='', max_length=80, null=0, primary_key=1, serialize=False, unique=1),
        ),
    ]
